// <auto-generated />
namespace Proyecto_PAA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bdatos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bdatos));
        
        string IMigrationMetadata.Id
        {
            get { return "202006300548502_bdatos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
