// <auto-generated />
namespace Proyecto_PAA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class creaciontablaprioridad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creaciontablaprioridad));
        
        string IMigrationMetadata.Id
        {
            get { return "202006190446126_creaciontablaprioridad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
